//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 6/23/2013 1:23:29 AM
namespace TopCarrotMobile.TopCarrotServiceReference
{
    
    /// <summary>
    /// There are no comments for TopCarrotEntities in the schema.
    /// </summary>
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    public partial class TopCarrotEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new TopCarrotEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public TopCarrotEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("TopCarrotModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("TopCarrotMobile.TopCarrotServiceReference", typeName.Substring(14)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("TopCarrotMobile.TopCarrotServiceReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("TopCarrotModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for CommodityPluCodes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CommodityPluCode> CommodityPluCodes
        {
            get
            {
                if ((this._CommodityPluCodes == null))
                {
                    this._CommodityPluCodes = base.CreateQuery<CommodityPluCode>("CommodityPluCodes");
                }
                return this._CommodityPluCodes;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CommodityPluCode> _CommodityPluCodes;
        /// <summary>
        /// There are no comments for CommodityPluCodes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCommodityPluCodes(CommodityPluCode commodityPluCode)
        {
            base.AddObject("CommodityPluCodes", commodityPluCode);
        }
    }
    /// <summary>
    /// There are no comments for TopCarrotModel.CommodityPluCode in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PLU
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CommodityPluCodes")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("PLU")]
    public partial class CommodityPluCode : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CommodityPluCode object.
        /// </summary>
        /// <param name="pLUId">Initial value of PLUId.</param>
        /// <param name="pLU">Initial value of PLU.</param>
        /// <param name="dateEntered">Initial value of DateEntered.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CommodityPluCode CreateCommodityPluCode(int pLUId, string pLU, global::System.DateTime dateEntered)
        {
            CommodityPluCode commodityPluCode = new CommodityPluCode();
            commodityPluCode.PLUId = pLUId;
            commodityPluCode.PLU = pLU;
            commodityPluCode.DateEntered = dateEntered;
            return commodityPluCode;
        }
        /// <summary>
        /// There are no comments for Property PLUId in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PLUId
        {
            get
            {
                return this._PLUId;
            }
            set
            {
                this.OnPLUIdChanging(value);
                this._PLUId = value;
                this.OnPLUIdChanged();
                this.OnPropertyChanged("PLUId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PLUId;
        partial void OnPLUIdChanging(int value);
        partial void OnPLUIdChanged();
        /// <summary>
        /// There are no comments for Property PLU in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PLU
        {
            get
            {
                return this._PLU;
            }
            set
            {
                this.OnPLUChanging(value);
                this._PLU = value;
                this.OnPLUChanged();
                this.OnPropertyChanged("PLU");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PLU;
        partial void OnPLUChanging(string value);
        partial void OnPLUChanged();
        /// <summary>
        /// There are no comments for Property Commodity in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Commodity
        {
            get
            {
                return this._Commodity;
            }
            set
            {
                this.OnCommodityChanging(value);
                this._Commodity = value;
                this.OnCommodityChanged();
                this.OnPropertyChanged("Commodity");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Commodity;
        partial void OnCommodityChanging(string value);
        partial void OnCommodityChanged();
        /// <summary>
        /// There are no comments for Property Variety in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Variety
        {
            get
            {
                return this._Variety;
            }
            set
            {
                this.OnVarietyChanging(value);
                this._Variety = value;
                this.OnVarietyChanged();
                this.OnPropertyChanged("Variety");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Variety;
        partial void OnVarietyChanging(string value);
        partial void OnVarietyChanged();
        /// <summary>
        /// There are no comments for Property Size in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Size
        {
            get
            {
                return this._Size;
            }
            set
            {
                this.OnSizeChanging(value);
                this._Size = value;
                this.OnSizeChanged();
                this.OnPropertyChanged("Size");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Size;
        partial void OnSizeChanging(string value);
        partial void OnSizeChanged();
        /// <summary>
        /// There are no comments for Property Restrictions in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Restrictions
        {
            get
            {
                return this._Restrictions;
            }
            set
            {
                this.OnRestrictionsChanging(value);
                this._Restrictions = value;
                this.OnRestrictionsChanged();
                this.OnPropertyChanged("Restrictions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Restrictions;
        partial void OnRestrictionsChanging(string value);
        partial void OnRestrictionsChanged();
        /// <summary>
        /// There are no comments for Property Botanical in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Botanical
        {
            get
            {
                return this._Botanical;
            }
            set
            {
                this.OnBotanicalChanging(value);
                this._Botanical = value;
                this.OnBotanicalChanged();
                this.OnPropertyChanged("Botanical");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Botanical;
        partial void OnBotanicalChanging(string value);
        partial void OnBotanicalChanged();
        /// <summary>
        /// There are no comments for Property VarietyInfo in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VarietyInfo
        {
            get
            {
                return this._VarietyInfo;
            }
            set
            {
                this.OnVarietyInfoChanging(value);
                this._VarietyInfo = value;
                this.OnVarietyInfoChanged();
                this.OnPropertyChanged("VarietyInfo");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VarietyInfo;
        partial void OnVarietyInfoChanging(string value);
        partial void OnVarietyInfoChanged();
        /// <summary>
        /// There are no comments for Property RevDate in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> RevDate
        {
            get
            {
                return this._RevDate;
            }
            set
            {
                this.OnRevDateChanging(value);
                this._RevDate = value;
                this.OnRevDateChanged();
                this.OnPropertyChanged("RevDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _RevDate;
        partial void OnRevDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnRevDateChanged();
        /// <summary>
        /// There are no comments for Property DateEntered in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime DateEntered
        {
            get
            {
                return this._DateEntered;
            }
            set
            {
                this.OnDateEnteredChanging(value);
                this._DateEntered = value;
                this.OnDateEnteredChanged();
                this.OnPropertyChanged("DateEntered");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _DateEntered;
        partial void OnDateEnteredChanging(global::System.DateTime value);
        partial void OnDateEnteredChanged();
        /// <summary>
        /// There are no comments for Property LastUpdated in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return this._LastUpdated;
            }
            set
            {
                this.OnLastUpdatedChanging(value);
                this._LastUpdated = value;
                this.OnLastUpdatedChanged();
                this.OnPropertyChanged("LastUpdated");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();
        /// <summary>
        /// There are no comments for Property GM in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> GM
        {
            get
            {
                return this._GM;
            }
            set
            {
                this.OnGMChanging(value);
                this._GM = value;
                this.OnGMChanged();
                this.OnPropertyChanged("GM");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _GM;
        partial void OnGMChanging(global::System.Nullable<bool> value);
        partial void OnGMChanged();
        /// <summary>
        /// There are no comments for Property GeneticModificationInfo in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GeneticModificationInfo
        {
            get
            {
                return this._GeneticModificationInfo;
            }
            set
            {
                this.OnGeneticModificationInfoChanging(value);
                this._GeneticModificationInfo = value;
                this.OnGeneticModificationInfoChanged();
                this.OnPropertyChanged("GeneticModificationInfo");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GeneticModificationInfo;
        partial void OnGeneticModificationInfoChanging(string value);
        partial void OnGeneticModificationInfoChanged();
        /// <summary>
        /// There are no comments for Property OriginCountry in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OriginCountry
        {
            get
            {
                return this._OriginCountry;
            }
            set
            {
                this.OnOriginCountryChanging(value);
                this._OriginCountry = value;
                this.OnOriginCountryChanged();
                this.OnPropertyChanged("OriginCountry");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OriginCountry;
        partial void OnOriginCountryChanging(string value);
        partial void OnOriginCountryChanged();
        /// <summary>
        /// There are no comments for Property Season in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Season
        {
            get
            {
                return this._Season;
            }
            set
            {
                this.OnSeasonChanging(value);
                this._Season = value;
                this.OnSeasonChanged();
                this.OnPropertyChanged("Season");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Season;
        partial void OnSeasonChanging(string value);
        partial void OnSeasonChanged();
        /// <summary>
        /// There are no comments for Property Seasonal in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Seasonal
        {
            get
            {
                return this._Seasonal;
            }
            set
            {
                this.OnSeasonalChanging(value);
                this._Seasonal = value;
                this.OnSeasonalChanged();
                this.OnPropertyChanged("Seasonal");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Seasonal;
        partial void OnSeasonalChanging(global::System.Nullable<bool> value);
        partial void OnSeasonalChanged();
        /// <summary>
        /// There are no comments for Property Climate in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Climate
        {
            get
            {
                return this._Climate;
            }
            set
            {
                this.OnClimateChanging(value);
                this._Climate = value;
                this.OnClimateChanged();
                this.OnPropertyChanged("Climate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Climate;
        partial void OnClimateChanging(string value);
        partial void OnClimateChanged();
        /// <summary>
        /// There are no comments for Property CommodityType in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CommodityType
        {
            get
            {
                return this._CommodityType;
            }
            set
            {
                this.OnCommodityTypeChanging(value);
                this._CommodityType = value;
                this.OnCommodityTypeChanged();
                this.OnPropertyChanged("CommodityType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CommodityType;
        partial void OnCommodityTypeChanging(string value);
        partial void OnCommodityTypeChanged();
        /// <summary>
        /// There are no comments for Property Image1 in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Image1
        {
            get
            {
                return this._Image1;
            }
            set
            {
                this.OnImage1Changing(value);
                this._Image1 = value;
                this.OnImage1Changed();
                this.OnPropertyChanged("Image1");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Image1;
        partial void OnImage1Changing(string value);
        partial void OnImage1Changed();
        /// <summary>
        /// There are no comments for Property Image2 in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Image2
        {
            get
            {
                return this._Image2;
            }
            set
            {
                this.OnImage2Changing(value);
                this._Image2 = value;
                this.OnImage2Changed();
                this.OnPropertyChanged("Image2");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Image2;
        partial void OnImage2Changing(string value);
        partial void OnImage2Changed();
        /// <summary>
        /// There are no comments for Property Image3 in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Image3
        {
            get
            {
                return this._Image3;
            }
            set
            {
                this.OnImage3Changing(value);
                this._Image3 = value;
                this.OnImage3Changed();
                this.OnPropertyChanged("Image3");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Image3;
        partial void OnImage3Changing(string value);
        partial void OnImage3Changed();
        /// <summary>
        /// There are no comments for Property Image4 in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Image4
        {
            get
            {
                return this._Image4;
            }
            set
            {
                this.OnImage4Changing(value);
                this._Image4 = value;
                this.OnImage4Changed();
                this.OnPropertyChanged("Image4");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Image4;
        partial void OnImage4Changing(string value);
        partial void OnImage4Changed();
        /// <summary>
        /// There are no comments for Property InfoURL1 in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string InfoURL1
        {
            get
            {
                return this._InfoURL1;
            }
            set
            {
                this.OnInfoURL1Changing(value);
                this._InfoURL1 = value;
                this.OnInfoURL1Changed();
                this.OnPropertyChanged("InfoURL1");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _InfoURL1;
        partial void OnInfoURL1Changing(string value);
        partial void OnInfoURL1Changed();
        /// <summary>
        /// There are no comments for Property InfoURL2 in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string InfoURL2
        {
            get
            {
                return this._InfoURL2;
            }
            set
            {
                this.OnInfoURL2Changing(value);
                this._InfoURL2 = value;
                this.OnInfoURL2Changed();
                this.OnPropertyChanged("InfoURL2");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _InfoURL2;
        partial void OnInfoURL2Changing(string value);
        partial void OnInfoURL2Changed();
        /// <summary>
        /// There are no comments for Property InfoURL3 in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string InfoURL3
        {
            get
            {
                return this._InfoURL3;
            }
            set
            {
                this.OnInfoURL3Changing(value);
                this._InfoURL3 = value;
                this.OnInfoURL3Changed();
                this.OnPropertyChanged("InfoURL3");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _InfoURL3;
        partial void OnInfoURL3Changing(string value);
        partial void OnInfoURL3Changed();
        /// <summary>
        /// There are no comments for Property InfoURL4 in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string InfoURL4
        {
            get
            {
                return this._InfoURL4;
            }
            set
            {
                this.OnInfoURL4Changing(value);
                this._InfoURL4 = value;
                this.OnInfoURL4Changed();
                this.OnPropertyChanged("InfoURL4");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _InfoURL4;
        partial void OnInfoURL4Changing(string value);
        partial void OnInfoURL4Changed();
        /// <summary>
        /// There are no comments for Property UpdatedByUserID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UpdatedByUserID
        {
            get
            {
                return this._UpdatedByUserID;
            }
            set
            {
                this.OnUpdatedByUserIDChanging(value);
                this._UpdatedByUserID = value;
                this.OnUpdatedByUserIDChanged();
                this.OnPropertyChanged("UpdatedByUserID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UpdatedByUserID;
        partial void OnUpdatedByUserIDChanging(string value);
        partial void OnUpdatedByUserIDChanged();
        /// <summary>
        /// There are no comments for Property GovernmentRestricted in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> GovernmentRestricted
        {
            get
            {
                return this._GovernmentRestricted;
            }
            set
            {
                this.OnGovernmentRestrictedChanging(value);
                this._GovernmentRestricted = value;
                this.OnGovernmentRestrictedChanged();
                this.OnPropertyChanged("GovernmentRestricted");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _GovernmentRestricted;
        partial void OnGovernmentRestrictedChanging(global::System.Nullable<bool> value);
        partial void OnGovernmentRestrictedChanged();
        /// <summary>
        /// There are no comments for Property Publish in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Publish
        {
            get
            {
                return this._Publish;
            }
            set
            {
                this.OnPublishChanging(value);
                this._Publish = value;
                this.OnPublishChanged();
                this.OnPropertyChanged("Publish");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Publish;
        partial void OnPublishChanging(global::System.Nullable<bool> value);
        partial void OnPublishChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
